// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRM_vdWgOIApzSqP_em-d5865Bl7RgYUQ',
    appId: '1:467877661436:web:4d80cae29d7085d5c66579',
    messagingSenderId: '467877661436',
    projectId: 'pictpo',
    authDomain: 'pictpo.firebaseapp.com',
    storageBucket: 'pictpo.appspot.com',
    measurementId: 'G-KYM55LSYJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIOX-fpPRSKVnggBxMLKnZFyZO6eldiI0',
    appId: '1:467877661436:android:ab74758f5c0d14f0c66579',
    messagingSenderId: '467877661436',
    projectId: 'pictpo',
    storageBucket: 'pictpo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOOisYtXKODsgSAdhJ401SliB1LOwAEpU',
    appId: '1:467877661436:ios:7dedf0353e0cc7b7c66579',
    messagingSenderId: '467877661436',
    projectId: 'pictpo',
    storageBucket: 'pictpo.appspot.com',
    iosClientId: '467877661436-11fup2ejfeddtcp6dnrqh1nqhcrv7e5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.pictpo',
  );
}
